-- =============================================================================
--  工地看板 Site Board — Database Schema Reference
-- =============================================================================
--
--  STATUS: PROPOSED / NOT YET IMPLEMENTED
--
--  The current backend (src/backend/) uses NO database. All state is held
--  in-memory in src/backend/mock_data.py::DataStore:
--      * self.events : collections.deque(maxlen=60)   (the event log)
--      * SITES / _ALERTS / _HOURLY_TREND / ...         (module-level Python lists)
--  It is regenerated by a live simulator and lost on process restart. This is
--  intentional for the demo — spec §11 leaves source-of-truth/persistence to
--  the 車牌管理平台 / 人臉辨識平台.
--
--  This file is the schema you would create when replacing DataStore with a
--  real store. Every table/column maps 1:1 to a Pydantic model in
--  src/backend/models.py (spec §8.2 欄位建議). Aggregates that the spec
--  computes on the fly (OverviewKPI) are modelled as VIEWS, not tables.
--
--  DIALECT: PostgreSQL 14+. SQLite adaptation notes are inline (-- SQLite:).
--  Conventions: snake_case (matches the API JSON), UTC TIMESTAMPTZ stored;
--  the API serialises event_time as "HH:MM:SS" (spec §8.2, precise to sec).
-- =============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Master / lookup tables
--    (Owned by external platforms per spec §10; mirrored here read-only so the
--     board can resolve names and the event log can carry FKs.)
-- ----------------------------------------------------------------------------

-- Construction sites — source: src/backend/mock_data.py::SITES
CREATE TABLE site (
    site_id        VARCHAR(16)  PRIMARY KEY,              -- e.g. 'A03'
    site_name      VARCHAR(64)  NOT NULL,                 -- 'A03 機電棟工區'
    status         VARCHAR(8)   NOT NULL DEFAULT 'normal' -- SiteStatus
                   CHECK (status IN ('normal','alert','delay')),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- SQLite: VARCHAR -> TEXT, TIMESTAMPTZ -> TEXT (ISO-8601), now() -> CURRENT_TIMESTAMP

-- Contractors (承攬商) referenced by events. Names appear free-text in the
-- mock; a lookup table de-dupes them and lets the alert wall group by vendor.
CREATE TABLE contractor (
    contractor_id  SERIAL       PRIMARY KEY,              -- SQLite: INTEGER PK AUTOINCREMENT
    name           VARCHAR(64)  NOT NULL UNIQUE           -- '大榮土木'
);

-- ----------------------------------------------------------------------------
-- 2. Event log  — core table. Model: src/backend/models.py::Event (spec §8.2)
--    This is the single source the board polls / streams (SSE) from.
-- ----------------------------------------------------------------------------
CREATE TABLE event (
    event_id           VARCHAR(48)  PRIMARY KEY,          -- 事件唯一編號 (避免重複顯示)
    site_id            VARCHAR(16)  NOT NULL REFERENCES site(site_id),
    site_name          VARCHAR(64)  NOT NULL,             -- denormalised for fast board reads
    event_type         VARCHAR(10)  NOT NULL              -- EventType
                       CHECK (event_type IN ('vehicle','personnel')),
    direction          VARCHAR(3)   NOT NULL              -- Direction
                       CHECK (direction IN ('IN','OUT')),
    event_time         TIMESTAMPTZ  NOT NULL,             -- 發生時間, 精確到秒
    display_name       VARCHAR(64)  NOT NULL,             -- 車牌號碼 或 人員姓名
    secondary_id       VARCHAR(32),                       -- 工號 / UNKNOWN 流水號 (nullable)
    contractor_id      INTEGER      REFERENCES contractor(contractor_id),
    contractor         VARCHAR(64)  NOT NULL DEFAULT '',  -- raw name (kept for replay)
    detail             VARCHAR(128) NOT NULL DEFAULT '',  -- 車型 / 職務 · 證照
    status             VARCHAR(16)  NOT NULL,             -- 白名單/黑名單/陌生/通行/拒絕/證照過期...
    status_type        VARCHAR(12)  NOT NULL              -- StatusType (drives colour rule §2)
                       CHECK (status_type IN
                              ('whitelist','pass','stranger','alert','blacklist')),
    snapshot_url       TEXT,                              -- 主截圖 (人臉/車輛全景), nullable §11
    plate_snapshot_url TEXT,                              -- 車牌小圖, vehicle only, nullable
    access_result      VARCHAR(16)  NOT NULL DEFAULT '',  -- AccessResult: opened/denied/manual_check/api_no_response
    -- AI explainability layer (demo: 信心度 / 判定依據 / 資料來源)
    confidence         NUMERIC(4,3) CHECK (confidence IS NULL OR
                                           (confidence >= 0 AND confidence <= 1)),
    why                TEXT,
    source             VARCHAR(64),
    ingested_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- Board query patterns -> indexes:
CREATE INDEX ix_event_site_time   ON event (site_id, event_time DESC);   -- §8.1 events/latest
CREATE INDEX ix_event_time        ON event (event_time DESC);            -- ALL-sites feed
CREATE INDEX ix_event_status_type ON event (status_type, event_time DESC); -- alert wall §5
CREATE INDEX ix_event_type_site   ON event (event_type, site_id, event_time DESC);
-- SQLite: drop SERIAL/REFERENCES if running file-only; keep the indexes.

-- ----------------------------------------------------------------------------
-- 3. Per-site daily statistics
--    Model: src/backend/models.py::SiteSummary (spec §8.1 sites/{id}/summary)
--    people_in/out & vehicle_in/out are daily cumulative; *_inside are live.
-- ----------------------------------------------------------------------------
CREATE TABLE site_daily_stat (
    site_id          VARCHAR(16) NOT NULL REFERENCES site(site_id),
    stat_date        DATE        NOT NULL,                -- 本日 (board resets at 00:00)
    people_in        INTEGER     NOT NULL DEFAULT 0,
    people_out       INTEGER     NOT NULL DEFAULT 0,
    people_inside    INTEGER     NOT NULL DEFAULT 0,      -- 即時在場 (去重後估算)
    vehicle_in       INTEGER     NOT NULL DEFAULT 0,
    vehicle_out      INTEGER     NOT NULL DEFAULT 0,
    vehicle_inside   INTEGER     NOT NULL DEFAULT 0,
    alert_count      INTEGER     NOT NULL DEFAULT 0,
    last_update_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (site_id, stat_date)
);

-- ----------------------------------------------------------------------------
-- 4. Hourly trend  — Model: HourlyTrendPoint (spec §6 / §8.1 trends/hourly)
-- ----------------------------------------------------------------------------
CREATE TABLE hourly_trend (
    site_id     VARCHAR(16) NOT NULL REFERENCES site(site_id),
    stat_date   DATE        NOT NULL,
    hour        SMALLINT    NOT NULL CHECK (hour BETWEEN 0 AND 23), -- "00".."23"
    people_in   INTEGER     NOT NULL DEFAULT 0,
    people_out  INTEGER     NOT NULL DEFAULT 0,
    vehicle_in  INTEGER     NOT NULL DEFAULT 0,
    vehicle_out INTEGER     NOT NULL DEFAULT 0,
    PRIMARY KEY (site_id, stat_date, hour)
);

-- 4b. AI forecast cone — Model: HourlyForecastPoint (demo ch.13 預測信賴帶)
CREATE TABLE hourly_forecast (
    site_id            VARCHAR(16) NOT NULL REFERENCES site(site_id),
    stat_date          DATE        NOT NULL,
    hour               SMALLINT    NOT NULL CHECK (hour BETWEEN 0 AND 23),
    people_in_forecast INTEGER     NOT NULL,
    people_in_upper    INTEGER     NOT NULL,              -- 信賴帶上界
    people_in_lower    INTEGER     NOT NULL,              -- 信賴帶下界
    model              VARCHAR(64) NOT NULL DEFAULT '',
    PRIMARY KEY (site_id, stat_date, hour)
);

-- ----------------------------------------------------------------------------
-- 5. Alert wall  — Model: Alert + AlertCost (spec §5 / 模板 p.10)
--    cost.fp / cost.fn inlined; suggestions[] -> child table (5b).
-- ----------------------------------------------------------------------------
CREATE TABLE alert (
    alert_id         VARCHAR(48)  PRIMARY KEY,
    type             VARCHAR(12)  NOT NULL                -- priority: blacklist/expired > api_delay > stranger > ...
                     CHECK (type IN ('blacklist','expired','stranger','api_delay')),
    target           VARCHAR(64)  NOT NULL,               -- 車牌 / 姓名 / API 名稱
    detail           VARCHAR(128) NOT NULL DEFAULT '',
    site_id          VARCHAR(16)  NOT NULL REFERENCES site(site_id),
    confidence       NUMERIC(4,3) CHECK (confidence IS NULL OR
                                         (confidence >= 0 AND confidence <= 1)),
    why              TEXT         NOT NULL DEFAULT '',
    cost_fp          TEXT         NOT NULL DEFAULT '',     -- 誤判代價 (False Positive)
    cost_fn          TEXT         NOT NULL DEFAULT '',     -- 漏判代價 (False Negative)
    occurrence       VARCHAR(32)  NOT NULL DEFAULT '',     -- '7 日內第 3 次'
    occurrence_count INTEGER      NOT NULL DEFAULT 1,
    related_event_id VARCHAR(48)  REFERENCES event(event_id),
    resolved         BOOLEAN      NOT NULL DEFAULT FALSE,  -- 人類拍板 (採納/誤判)
    resolution       VARCHAR(16),                          -- 'adopted' | 'false_positive' | NULL
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_alert_open ON alert (resolved, created_at DESC);

-- 5b. Ordered AI suggestions for an alert (Alert.suggestions: list[str])
CREATE TABLE alert_suggestion (
    alert_id  VARCHAR(48)  NOT NULL REFERENCES alert(alert_id) ON DELETE CASCADE,
    seq       SMALLINT     NOT NULL,                       -- 1-based display order
    text      VARCHAR(128) NOT NULL,
    PRIMARY KEY (alert_id, seq)
);

-- ----------------------------------------------------------------------------
-- 6. System status time-series — Model: SystemStatus (spec §8.1 system/status)
--    Kept as a log so the board can show "最後成功更新時間" after a drop (§10).
-- ----------------------------------------------------------------------------
CREATE TABLE system_status (
    id                BIGSERIAL   PRIMARY KEY,             -- SQLite: INTEGER PK AUTOINCREMENT
    recorded_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    plate_api_status  VARCHAR(8)  NOT NULL CHECK (plate_api_status IN ('normal','delay','down')),
    face_api_status   VARCHAR(8)  NOT NULL CHECK (face_api_status  IN ('normal','delay','down')),
    last_success_time TIMESTAMPTZ NOT NULL,
    latency_seconds   INTEGER     NOT NULL DEFAULT 0,
    error_message     TEXT,
    api_online        INTEGER     NOT NULL DEFAULT 0,
    api_total         INTEGER     NOT NULL DEFAULT 0,
    cached_events     INTEGER     NOT NULL DEFAULT 0,
    version           VARCHAR(16) NOT NULL DEFAULT '1.0.0'
);
CREATE INDEX ix_system_status_time ON system_status (recorded_at DESC);

-- ----------------------------------------------------------------------------
-- 7. AI copilot summaries — Model: CopilotSummary (Agentic supervisor panel)
-- ----------------------------------------------------------------------------
CREATE TABLE copilot_summary (
    id           BIGSERIAL    PRIMARY KEY,
    site_id      VARCHAR(16)  REFERENCES site(site_id),    -- NULL = 全部工地
    headline     VARCHAR(64)  NOT NULL,
    body         TEXT         NOT NULL,
    sources      VARCHAR(128) NOT NULL DEFAULT '',
    model        VARCHAR(64)  NOT NULL DEFAULT '',
    generated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 8. Derived views (spec computes these on the fly — not stored)
-- ----------------------------------------------------------------------------

-- OverviewKPI (spec §4.1 上方 KPI) = aggregate over today's site_daily_stat.
CREATE VIEW v_overview_kpi AS
SELECT
    COALESCE(SUM(people_in),     0) AS people_in,
    COALESCE(SUM(people_out),    0) AS people_out,
    COALESCE(SUM(people_inside), 0) AS people_inside,
    COALESCE(SUM(vehicle_in),    0) AS vehicle_in,
    COALESCE(SUM(vehicle_out),   0) AS vehicle_out,
    COALESCE(SUM(vehicle_inside),0) AS vehicle_inside,
    COALESCE(SUM(alert_count),   0) AS alert_count
FROM site_daily_stat
WHERE stat_date = CURRENT_DATE;

-- Latest events feed for the board (spec §8.1 events/latest, default 20).
CREATE VIEW v_latest_events AS
SELECT *
FROM event
ORDER BY event_time DESC;

COMMIT;

-- =============================================================================
--  Table inventory
-- -----------------------------------------------------------------------------
--   site               master   construction sites
--   contractor         lookup   承攬商 names (de-duped)
--   event              log      every 進出事件 (board's source of truth)   §8.2
--   site_daily_stat    agg      per-site daily KPI counters                §8.1
--   hourly_trend       agg      0-23h people/vehicle in/out                §6
--   hourly_forecast    agg      AI forecast + confidence cone              ch.13
--   alert              log      異常事件牆 cards + human resolution         §5
--   alert_suggestion   child    ordered AI next-step suggestions
--   system_status      log      plate/face API health time-series          §8.1
--   copilot_summary    log      AI 副駕駛 summaries
--   v_overview_kpi     view     cross-site KPI rollup (today)
--   v_latest_events    view     newest-first event feed
-- =============================================================================
